# Generated by Django 5.1.6 on 2025-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_studentprofile_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='research_interests',
            field=models.TextField(blank=True, help_text="Research areas and thesis topics this supervisor can guide (e.g., 'AI, Machine Learning, Web Development')", null=True),
        ),
    ]
