# Generated by Django 5.1.6 on 2025-11-06 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('topic_enhancement', 'Topic Enhancement'), ('chatbot_message', 'Chatbot Message')], max_length=20)),
                ('date', models.DateField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Window',
                'verbose_name_plural': 'AI Usage Windows',
                'indexes': [models.Index(fields=['user', 'feature_type', 'date'], name='ai_chatbot__user_id_0de26c_idx')],
                'unique_together': {('user', 'feature_type', 'date')},
            },
        ),
    ]
